services:
    postgres:
        image: postgres:16
        ports:
            - "5432:5432"
        volumes:
            - /Users/data/postgres:/data/postgres
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=home-inspections
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres"]
          interval: 5s
          timeout: 5s
          retries: 5

    server:
      build:
        context: .
        dockerfile: Dockerfile.dev
      env_file:
        - .env.development
      environment:
        - NODE_ENV=development
      volumes:
        - ./src:/app/src
        - ./types:/app/types
      depends_on:
        postgres:
          condition: service_healthy
      ports:
        - '9000:9000'